# Generated by Django 4.0.3 on 2022-03-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0019_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('cat_id', models.CharField(max_length=100)),
            ],
        ),
    ]
