# Generated by Django 4.0.3 on 2022-03-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0020_mainproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='cat_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
