# Generated by Django 4.0.3 on 2022-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0021_mainproduct_cat_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_id', models.CharField(max_length=100)),
                ('cat_name', models.CharField(max_length=100)),
            ],
        ),
    ]
